version: 2

updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: UTC
    labels:
      - dependencies
      - ruby
     # Disable all pull requests
     open-pull-requests-limit: 0

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: UTC
    labels:
      - dependencies
      - javascript
    # Disable all pull requests
    open-pull-requests-limit: 0
