require: rubocop-rspec

Rails:
  Enabled: true

AllCops:
  NewCops: enable

  TargetRubyVersion: 2.6
  Exclude:
    - bin/*
    - db/migrate/**/*
    - db/schema.rb
    - test/**/*
    - tmp/**/*
    - views/**/*
    - vendor/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/routes.rb
    - Guardfile
    - config/environments/*
    - config/initializers/rails_admin.rb

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

Layout/LineLength:
  Max: 140

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

RSpec/ExampleLength:
  Exclude:
    - spec/services/proforma_service/convert_exercise_to_task_spec.rb
    - spec/services/proforma_service/convert_task_to_exercise_spec.rb

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Max: 14

RSpec/EmptyExampleGroup:
  Exclude:
    - spec/models/file_type_spec.rb

Style/Documentation:
  Enabled: false
