db:
    image: postgres
    ports:
     - "54320:5432"
web:
    build: .
    ports:
        - "7500:7500"
    command:
        bash -c "rails s -b 0.0.0.0" #"rm /codeharbor/tmp/pids/server.pid && rails s -b 0.0.0.0"
    environment:
        - RAILS_ENV=development
        - RACK_ENV=development
        - DATABASE_URL=postgres://postgres@db:5432/
    volumes:
        - .:/codeharbor
    links:
      - db