db:
    image: postgres
    ports:
     - "5432:5432"
web:
    build: .
    ports:
        - "3000:3000"
    command:
        bash -c "rails s -b 0.0.0.0" #"rm /codeharbor/tmp/pids/server.pid && rails s -b 0.0.0.0"
    environment:
        - RAILS_ENV=development
        - RACK_ENV=development
        - DATABASE_URL=postgres://postgres@db:5432/
        - SSH_AUTH_SOCK=/ssh-auth-sock
    #volumes:
        #- ./:/codeharbor/
        #- $SSH_AUTH_SOCK:/tmp/ssh-agent # Forward local machine SSH key to docker
    volumes_from:
        - ssh-auth-sock
    links:
      - db