db:
    image: postgres
    ports:
     - "5432:5432"
    restart: always
web:
    image: openhpidev/codeharbor
    container_name: web1
    ports:
        - "3000:3000"
    command:
        bash -c "rails s -b 0.0.0.0"
    restart: unless-stopped
    environment:
        - RAILS_ENV=production
        - RACK_ENV=production
        - DATABASE_URL=postgres://postgres@db:5432/
    links:
      - db