default: &default
  default_options:
    from: sender@host.com
  delivery_method: :smtp

development:
  <<: *default
  default_url_options:
    host: localhost

production:
  <<: *default
  default_url_options:
    host: CHANGEME
  delivery_method: :sendmail

test:
  <<: *default
  default_url_options:
    host: localhost
    port: 3000
