default: &default

development:
  <<: *default
  default_url_options:
    host: localhost
    port: 7500

production:
  <<: *default

test:
  <<: *default
  default_url_options:
    host: localhost
    port: 3000
  delivery_method: :test